---
# tasks file for docker-rhel

- include: os/rhel.yml
  when: ansible_os_family == 'RedHat'

- name: Install Docker
  package:
    name: "docker-{{ docker_edition }}"
    state: latest
  become: yes

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes